name: telegram_bot
description: A Telegram bot for the telegram channel
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.8.1

# Add regular dependencies here.
dependencies:
  teledart: ^0.6.1 
  dotenv: ^4.2.0

dev_dependencies: 
  lints: ^5.0.0
  test: ^1.24.0
